### ISSUE TITLE
Not redirecting on failure

### ISSUE THREAD

**Issue by John-Hayes-Reed** [katafrakt/omniauth-hanami#1]
On a failure of invalid credentials (for `provider: 'hanami'`, not a github integrated solution etc), the authentication fails loudly throwing an error with no sensible way to rescue from. The tests written show tests to ensure that a redirect is done on the failure of an authentication however in practice I can not see this happening.

Any chance for some help on how to resolve this issue?

**Comment by katafrakt** [comment]
Hi @John-Hayes-Reed  and sorry for a delay (for some reason I'm not getting any notification from GH when someone creates issue or pull request in my repository). What you describe, seems to be [an Omniauth thing](https://github.com/omniauth/omniauth/wiki/FAQ#omniauthfailureendpoint-does-not-redirect-in-development-mode) and on purpose. I'm not sure how can this behaviour be safely overridden by the Hanami provider. Meanwhile, [I updated example application](https://gitlab.com/katafrakt/hanami_omniauth_example/commit/942673452785371129b2553b3eef8a149b126d59) with solution suggested by Omniauth FAQ.
